# Generated by Django 3.2.7 on 2021-11-25 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(default='US', max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('zone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=35, unique=True)),
                ('country_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.country')),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=6)),
                ('time_start', models.BigIntegerField()),
                ('gmt_offset', models.IntegerField()),
                ('dst', models.CharField(max_length=1)),
                ('zone_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('iata', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('elevation', models.SmallIntegerField(blank=True)),
                ('lat', models.DecimalField(decimal_places=11, max_digits=14)),
                ('long', models.DecimalField(decimal_places=11, max_digits=14)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_edited', models.DateTimeField(blank=True)),
                ('zone_name', models.ForeignKey(blank=True, db_column='zone_name', default='Blank', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.zone', to_field='zone_name')),
            ],
        ),
    ]
