# Generated by Django 3.2.7 on 2022-07-31 01:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineList',
            fields=[
                ('airlinecode', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airlinename', models.CharField(blank=True, max_length=25, null=True)),
                ('airlinedescription', models.CharField(blank=True, max_length=200, null=True)),
                ('airlinesize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AirlineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importdate', models.DateField(default=django.utils.timezone.now)),
                ('rawdata', tinymce.models.HTMLField()),
                ('airline', models.ForeignKey(blank=True, default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='airline.airlinelist')),
            ],
        ),
    ]
