# Generated by Django 3.2.7 on 2022-07-31 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlineschedule',
            name='rotationnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='airlineschedule',
            name='airline',
            field=models.ForeignKey(default='', max_length=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='airline.airlinelist'),
        ),
    ]
