# Generated by Django 3.2.7 on 2022-07-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20220731_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlineschedule',
            name='rotationnumber',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
