# Generated by Django 3.2.7 on 2021-12-10 19:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraftref',
            fields=[
                ('mfrcode', models.CharField(default='0', max_length=20, primary_key=True, serialize=False)),
                ('mfr', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('typeacft', models.IntegerField()),
                ('typeengine', models.IntegerField()),
                ('accat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('buildcertid', models.IntegerField()),
                ('numberengines', models.IntegerField()),
                ('numberseats', models.IntegerField()),
                ('acweight', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_edited', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('engcode', models.IntegerField(default='0', primary_key=True, serialize=False)),
                ('mfr', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('thrust', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_edited', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('nnumber', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('airworthdate', models.IntegerField(blank=True, null=True)),
                ('yearmfr', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 19, 51, 54, 587850), null=True)),
                ('date_edited', models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 10, 19, 51, 54, 587866), null=True)),
                ('engcode', models.ForeignKey(default='none', on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.engine')),
                ('mfrcode', models.ForeignKey(default='none', on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.aircraftref')),
            ],
        ),
    ]
