# Generated by Django 3.2.7 on 2021-12-12 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 17, 57, 7, 476327), null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 17, 57, 7, 476347), null=True),
        ),
    ]
