# Generated by Django 3.2.7 on 2021-12-12 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_auto_20211212_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 18, 31, 18, 927869), null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 18, 31, 18, 927890), null=True),
        ),
    ]
