# Generated by Django 3.2.7 on 2021-12-12 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_auto_20211212_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 18, 35, 33, 648575), null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 18, 35, 33, 648601), null=True),
        ),
    ]
