# Generated by Django 3.2.7 on 2021-12-12 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_auto_20211212_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 18, 39, 7, 561455), null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 12, 18, 39, 7, 561472), null=True),
        ),
    ]
