# Generated by Django 3.2.7 on 2022-04-25 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0007_auto_20211219_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='date_edited',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='engcode',
            field=models.ForeignKey(default=12345678, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.engine'),
        ),
        migrations.AlterField(
            model_name='master',
            name='mfrcode',
            field=models.ForeignKey(default=12345678, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.aircraftref'),
        ),
    ]
