# Generated by Django 3.2.7 on 2022-05-15 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0008_auto_20220425_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('type', models.CharField(default='0', max_length=20, primary_key=True, serialize=False)),
                ('numberengines', models.IntegerField(default=1)),
                ('land', models.BooleanField(default=True)),
                ('sea', models.BooleanField(default=False)),
                ('tailwheel', models.BooleanField(default=False)),
                ('turboprop', models.BooleanField(default=False)),
                ('complex', models.BooleanField(default=False)),
                ('highperformance', models.BooleanField(default=False)),
                ('turbofan', models.BooleanField(default=False)),
                ('turbine', models.BooleanField(default=False)),
                ('rotorcraft', models.BooleanField(default=False)),
                ('poweredlift', models.BooleanField(default=False)),
                ('numberseats', models.IntegerField(blank=True, null=True)),
                ('acweight', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_edited', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(blank=True)),
                ('date_edited', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewPlaneMaster',
            fields=[
                ('nnumber', models.CharField(default='0', max_length=50, primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_edited', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('aircraftmodel', models.ForeignKey(default=12345678, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.aircraftmodel')),
            ],
        ),
        migrations.AddField(
            model_name='aircraftmodel',
            name='mfr',
            field=models.ForeignKey(default=12345678, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.manufacture'),
        ),
    ]
