# Generated by Django 3.2.7 on 2022-05-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0009_auto_20220515_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftmodel',
            name='acweight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
