# Generated by Django 3.2.7 on 2022-05-30 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0010_alter_aircraftmodel_acweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='engcode',
        ),
        migrations.RemoveField(
            model_name='master',
            name='mfrcode',
        ),
        migrations.DeleteModel(
            name='Aircraftref',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
