# Generated by Django 3.2.7 on 2022-07-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0011_auto_20220530_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='newplanemaster',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
