# Generated by Django 3.2.7 on 2022-05-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0001_initial'),
        ('aircraft', '0010_alter_aircraftmodel_acweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('flightdate', models.DateField()),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('flightnum', models.IntegerField(blank=True, null=True)),
                ('deptime', models.TimeField(blank=True, null=True)),
                ('offtime', models.TimeField(blank=True, null=True)),
                ('ontime', models.TimeField(blank=True, null=True)),
                ('arrtime', models.TimeField(blank=True, null=True)),
                ('landings', models.IntegerField(blank=True, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hood', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('iap', models.IntegerField(blank=True, null=True)),
                ('typeofapproach', models.CharField(blank=True, max_length=10, null=True)),
                ('descriptionofapproach', models.CharField(blank=True, max_length=100, null=True)),
                ('holdnumber', models.IntegerField(blank=True, null=True)),
                ('holdboolean', models.BooleanField(blank=True, null=True)),
                ('pic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sic', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cfi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('crosscountry', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('solo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('daylandings', models.IntegerField(blank=True, null=True)),
                ('night', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nightlandings', models.IntegerField(blank=True, null=True)),
                ('printcomments', models.CharField(blank=True, max_length=1000)),
                ('personalcomments', models.CharField(blank=True, max_length=300)),
                ('ftd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ftdimc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sim', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('simimc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pcatd', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pcimc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('instructor', models.CharField(blank=True, max_length=45)),
                ('instructorid', models.IntegerField(blank=True, null=True)),
                ('student', models.CharField(blank=True, max_length=50)),
                ('studentid', models.IntegerField(blank=True, null=True)),
                ('captain', models.CharField(blank=True, max_length=50)),
                ('firstofficer', models.CharField(blank=True, max_length=50)),
                ('flightattendants', models.CharField(blank=True, max_length=50)),
                ('passengercount', models.IntegerField(blank=True, null=True)),
                ('scheduleddeparttime', models.TimeField(blank=True, null=True)),
                ('scheduledarrivaltime', models.TimeField(blank=True, null=True)),
                ('scheduledflight', models.BooleanField(blank=True, null=True)),
                ('aircraftId', models.ForeignKey(default='N1234DLH', on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.newplanemaster')),
                ('arrival', models.ForeignKey(blank=True, default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='icaoarrive', to='airport.airport')),
                ('departure', models.ForeignKey(blank=True, default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='icaodepart', to='airport.airport')),
                ('typeacft', models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.aircraftmodel')),
            ],
        ),
    ]
