# Generated by Django 3.2.7 on 2022-07-26 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttime',
            name='flightdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
