# Generated by Django 3.2.7 on 2021-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttime',
            name='arrtime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='deptime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='offtime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='ontime',
            field=models.TimeField(blank=True),
        ),
    ]
