# Generated by Django 3.2.7 on 2022-05-30 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_remove_flighttime_typeacft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttime',
            name='flightdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
