# Generated by Django 3.2.7 on 2022-08-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20220726_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttime',
            name='scheduledblock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
