# Generated by Django 3.2.7 on 2021-12-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_auto_20211212_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttime',
            name='crosscountry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='daylandings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='ftd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='ftdimc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='instructorid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='nightlandings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='passengercount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='pcatd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='pcimc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='scheduledarrivaltime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='scheduleddeparttime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='sim',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='simimc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='solo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='studentid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
