# Generated by Django 3.2.7 on 2022-05-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0011_auto_20220530_1546'),
        ('logbook', '0003_alter_flighttime_flightdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flighttime',
            name='typeacft',
            field=models.ForeignKey(default=123456789, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.aircraftmodel'),
        ),
    ]
