# Generated by Django 3.2.7 on 2021-12-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20211212_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttime',
            name='arrival',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='arrtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='cfi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='departure',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='deptime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='descriptionofapproach',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='dual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='flightnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='holdboolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='holdnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='hood',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='iap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='landings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='offtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='ontime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='pic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='route',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='sic',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='typeofapproach',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
