# Generated by Django 3.2.7 on 2021-12-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0004_auto_20211212_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttime',
            name='arrival',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='departure',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='route',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
