# Generated by Django 3.2.7 on 2021-12-19 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
        ('logbook', '0005_auto_20211212_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flighttime',
            name='arrival',
            field=models.ForeignKey(blank=True, default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='icaoarrive', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='flighttime',
            name='departure',
            field=models.ForeignKey(blank=True, default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='icaodepart', to='airport.airport'),
        ),
    ]
