# Generated by Django 3.2.7 on 2022-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211210_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='zulu',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
