# Generated by Django 3.2.7 on 2022-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_users_zulu'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='decimalplaces',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
