# Generated by Django 3.2.7 on 2022-06-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
        ('aircraft', '0011_auto_20220530_1546'),
        ('user', '0004_users_decimalplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cx',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='decimal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='time',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='defaultairplane',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='aircraft.aircraftmodel'),
        ),
        migrations.AlterField(
            model_name='users',
            name='defaultairport',
            field=models.ForeignKey(blank=True, default='', max_length=100, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='airport.airport'),
        ),
    ]
